version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: medichive_postgres
    environment:
      POSTGRES_DB: medichive_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Malani1963
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
